In [1]:
# Printing my name
print('"Hi"! My name is Phanindra.')

"Hi"! My name is Phanindra.


In [2]:
# Printing a quote using " "
print('"Make everyday a little less ordinary."-Anonymous')

"Make everyday a little less ordinary."-Anonymous


In [3]:
# Printing a required pattern
for i in [4,7,11]:
    for _ in range(i,12,2):
        print(end=' ')
    for _ in range(i):
        print(end='@')
    print()
    for _ in range(i+2,12,2):
        print(end=' ')
    print(end='{')
    for _ in range(i):
        print(end=' ')
    print('}')

    @@@@
   {    }
   @@@@@@@
  {       }
 @@@@@@@@@@@
{           }


In [4]:
# Checking whether two lists have same elements at an index
your_cloud_shapes=['circle','turtle','dolphin','truck','apple','spoon']
friend_cloud_shapes=['apple','turtle','spoon','truck','circle','dolphin']
for i in range(len(your_cloud_shapes)):
    if your_cloud_shapes[i]==friend_cloud_shapes[i]:
        print('We saw the same shape!')
    elif your_cloud_shapes[i]!=friend_cloud_shapes[i]:
        print('We saw different shapes this time.')

We saw different shapes this time.
We saw the same shape!
We saw different shapes this time.
We saw the same shape!
We saw different shapes this time.
We saw different shapes this time.


In [5]:
# Printing whether the elements are stored in List or Tuple
person=['Adrienne','Tache','brown','black','10','10']
print(person,'are stored in a list!')
animals=('cats','dogs','turtles','bunnies')
print(animals,'are stored in a tuple!')
colors=['red','orange','yellow','green','blue','indigo','violet']
print(colors,'are stored in a list!')

['Adrienne', 'Tache', 'brown', 'black', '10', '10'] are stored in a list!
('cats', 'dogs', 'turtles', 'bunnies') are stored in a tuple!
['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'] are stored in a list!


In [6]:
# Completing an expression which gives a result of 333
print(5**3+175+(3%4)*11)

333


In [7]:
# Printing the version of the numpy installed
import numpy as np
print(np.__version__)

1.20.1


In [8]:
# Creating a 1d array of numbers from 0 to 9
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Creating an array filled with zeroes
import numpy as np
zeroes=np.zeros(5, dtype=int)
print(zeroes)

[0 0 0 0 0]


In [10]:
# Creating an array with evenly spaced numbers
import numpy as np
evenspace=np.linspace(1,10,5)
print(evenspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
# Sorting an array
import numpy as np
srt=np.array([2,1,5,3,7,4,6,8])
print(np.sort(srt))

[1 2 3 4 5 6 7 8]


In [12]:
# Printing odd values in an array
import numpy as np
odd=np.array([0,1,2,3,4,5,6,7,8,9])
print('>array([{}])'.format(odd[odd%2==1]))

>array([[1 3 5 7 9]])


In [13]:
# Coverting 1d array to 2d array
import numpy as np
dim1=np.arange(10)
dim2=np.reshape(dim1,(2,-1))
print(dim2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
# Printing the unique values in an array
import numpy as np
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
print(np.unique(a))

[11 12 13 14 15 16 17 18 19 20]


In [15]:
# Reversing a 1d array
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(np.flipud(a))

[8 7 6 5 4 3 2 1]


In [16]:
# Length of strings
words=['cat','window','defenestrate']
for i in words:
    c=0
    for j in i:
        c+=1
    print('Length of',i,'is',c)

Length of cat is 3
Length of window is 6
Length of defenestrate is 12


In [17]:
# Iterating over the indices of a sequence
lst=['Mary','had','a','little','lamb']
for i in range(len(lst)):
    print(lst[i])

Mary
had
a
little
lamb


In [18]:
# Printing Ranks from 2 to 20
n=2
while n<=20:
    print(n,end=' ')
    n+=1

2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 

In [22]:
# Using pandas
import pandas as pd
titanic = pd.read_csv('titanic_lyst7308.csv')
print('Printing the first 10 rows from the last:')
print(titanic.tail(10),'\n\n')

print('Printing the first 10 rows from the beginning:')
print(titanic.head(10),'\n\n')

print('Filtering the passengers list who are older than 25 years old:')
print(titanic[titanic['age'] > 25],'\n\n')

print('Printing names of passengers who are older than 35 years old:')
print(titanic.loc[titanic['age'] > 35,'name'],'\n\n')

print('Printing the median of age, ticket and fare of the titanic passengers:')
print(titanic[['age','ticket', 'fare']].median(),'\n\n')

print('Printing the maximum, minimum, mean of age, ticket and fare of the titanic passengers respectively:')
print(titanic[['age','ticket', 'fare']].max(),'\n')
print(titanic[['age','ticket', 'fare']].min(),'\n')
print(titanic[['age','ticket', 'fare']].mean(),'\n')

print('Printing mean ticket fare for each of sex and cabin class:')
print(titanic.groupby(['sex', 'cabin'])['fare'].mean(),'\n\n')

print('Sorting the titanic csv file according to the age of passengers:')
print(titanic.sort_values(by=['age']),'\n')



Printing the first 10 rows from the last:
      pclass  survived                                     name     sex   age  \
1299       3         0                      Yasbeck, Mr. Antoni    male  27.0   
1300       3         1  Yasbeck, Mrs. Antoni (Selini Alexander)  female  15.0   
1301       3         0                     Youseff, Mr. Gerious    male  45.5   
1302       3         0                        Yousif, Mr. Wazli    male   NaN   
1303       3         0                    Yousseff, Mr. Gerious    male   NaN   
1304       3         0                     Zabour, Miss. Hileni  female  14.5   
1305       3         0                    Zabour, Miss. Thamine  female   NaN   
1306       3         0                Zakarian, Mr. Mapriededer    male  26.5   
1307       3         0                      Zakarian, Mr. Ortin    male  27.0   
1308       3         0                       Zimmerman, Mr. Leo    male  29.0   

      sibsp  parch  ticket     fare cabin embarked boat   body hom